#MadLib | Jackson Pike
adjective1 = input("Enter an adjective: ")
firstName = input("Female First Name: ")
adjective2 = input("Enter an adjective: ")
noun1 = input("Enter a noun: ")
verb1 = input("Enter a verb: ")
animal1 = input("Enter an animal: ")
verb2 = input("Enter a verb(-ing): ")
adverb1 = input("Enter an adverb: ")
adjective3 = input("Enter an adjective: ")
firstName2 = input("Enter a name: ")
adjective4 = input("Enter an adjective: ")
noun2 = input("Enter a noun: ")
verb3 = input("Enter a verb(-ing): ")
noun3 = input("Enter a plural noun: ")
verb4 = input("Enter a verb(-ing): ")

print("They say my school is haunted; my", adjective1, "friend", firstName)
print("says she saw a", adjective2, noun1, "floating at the end of the hall near")
print("the cafeteria. Some say if you", verb1, "down that hallway at night, you'll hear a", animal1)
print(verb2, adverb1, ". My", adjective3, "friend", firstName2, "saw a", adjective4, noun2, verb3)
print("under one of the tables once. I hope I never see any", noun3, verb4, "; eating lunch there is")
print("scary enough!")
input()
#Changed On GitHub
#Changed On Visual Studio Code
